title: 'Singapore Convention on Mediation'
description: 'Description Singapore Convention on Mediation'
url: 'https://www.singaporeconvention.org'
is_government: false
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
collections:
    about-convention:
        output: true
    about-conference:
        output: true
    sg-convention-week:
        output: true
    SCM-2019:
        output: true
    Events:
        output: true
resources_name: media
favicon: /images/favicon.png
google-analytics: UA-140220094-2
permalink: none
baseurl: ""
defaults:
    - scope:
        path: ""
      values:
        layout: page
